/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: MIT-0
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this
 * software and associated documentation files (the "Software"), to deal in the Software
 * without restriction, including without limitation the rights to use, copy, modify,
 * merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
 * permit persons to whom the Software is furnished to do so.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
 * PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
 * OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
 * SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

const TYPE_PATH = 'Path';
const TYPE_CLASS = 'Class'; 
const TYPE_FUNCTION = 'Function';
const EDGE_CONTAINS = 'contains';
const EDGE_CALL = 'calls';
const EDGE_EXTENDS = 'extends';


const PATH_META_DATA = 'path_metadata';
const CLASS_META_DATA = 'class_metadata';
const FUNC_META_DATA = 'function_metadata';

const CODE_GRAPH_TABLE = 'code-graph-table';
const GRAPH_FILES_TABLE = 'graph-files-table';

const CODE_GRAPH_TABLE_COLUMN_ID = 'id';
const CODE_GRAPH_TABLE_COLUMN_GITURL = 'gitUrl';
const CODE_GRAPH_TABLE_COLUMN_BRANCH = 'branch';
const CODE_GRAPH_TABLE_COLUMN_SUBFOLDER = 'subFolder';
const CODE_GRAPH_TABLE_COLUMN_FILE_FILTER = 'fileFilter';
const CODE_GRAPH_TABLE_COLUMN_UPDATE_TIME = 'updateTime';
const CODE_GRAPH_TABLE_COLUMN_STATUS = 'status';
const CODE_GRAPH_TABLE_COLUMN_DELETED = 'deleted';

const CODE_GRAPH_TABLE_STATUS_CODE_DOWNLOADING = 'CODE_DOWNLOADING';
const CODE_GRAPH_TABLE_STATUS_CODE_ANALYSING = 'CODE_ANALYSING';
const CODE_GRAPH_TABLE_STATUS_GRAPH_CREATING = 'GRAPH_CREATING';
const CODE_GRAPH_TABLE_STATUS_GRAPH_CREATED = 'GRAPH_CREATED';
const CODE_GRAPH_TABLE_STATUS_FAILED = 'FAILED';

const GRAPH_FILES_TABLE_COLUMN_GRAPH_ID = 'graphId';
const GRAPH_FILES_TABLE_COLUMN_FULL_PATH = 'fullPath';
const GRAPH_FILES_TABLE_COLUMN_SCANED = 'scaned';

let BEDROCK_API_PAUSE_TIME = 2500;

function setBedrockAPIPauseTime(time) {
  BEDROCK_API_PAUSE_TIME = time;
}

module.exports = {
  TYPE_PATH,
  TYPE_CLASS,
  TYPE_FUNCTION,
  EDGE_CONTAINS,
  EDGE_CALL,
  EDGE_EXTENDS,
  PATH_META_DATA,
  CLASS_META_DATA,
  FUNC_META_DATA,
  CODE_GRAPH_TABLE,
  GRAPH_FILES_TABLE,
  BEDROCK_API_PAUSE_TIME,

  CODE_GRAPH_TABLE_COLUMN_ID,
  CODE_GRAPH_TABLE_COLUMN_GITURL,
  CODE_GRAPH_TABLE_COLUMN_BRANCH,
  CODE_GRAPH_TABLE_COLUMN_SUBFOLDER,
  CODE_GRAPH_TABLE_COLUMN_FILE_FILTER,
  CODE_GRAPH_TABLE_COLUMN_UPDATE_TIME,
  CODE_GRAPH_TABLE_COLUMN_STATUS,
  CODE_GRAPH_TABLE_COLUMN_DELETED,

  CODE_GRAPH_TABLE_STATUS_CODE_DOWNLOADING,
  CODE_GRAPH_TABLE_STATUS_CODE_ANALYSING,
  CODE_GRAPH_TABLE_STATUS_GRAPH_CREATING,
  CODE_GRAPH_TABLE_STATUS_GRAPH_CREATED,
  CODE_GRAPH_TABLE_STATUS_FAILED,

  GRAPH_FILES_TABLE_COLUMN_GRAPH_ID,
  GRAPH_FILES_TABLE_COLUMN_FULL_PATH,
  GRAPH_FILES_TABLE_COLUMN_SCANED,
  setBedrockAPIPauseTime
}
